AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Cors: "'*'"

Resources:
  BypassFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: ./hello_world/
      Events:
        Callback:
          Type: Api
          Properties:
            Path: /proxy/{proxy+}
            Method: any
            RestApiId:
              Ref: BypassAPI
  BypassAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      DefinitionUri: ./swagger.json